sudo: false
language: go
go:
    - 1.6
go_import_path: github.com
install:
    - go get github.com/gorilla/mux
    - go get github.com/gorilla/context
    - go get gopkg.in/redis.v4
    - go get gopkg.in/bsm/ratelimit.v1
services:
    - docker
before_install:
    - export GOPATH=$HOME/gopath/src/github.com
    - sleep 15
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o blob
    - sleep 5
    - docker build -t awaseem/blob:$TRAVIS_BRANCH-$TRAVIS_COMMIT .
    - sleep 5
    - docker push awaseem/blob:$TRAVIS_BRANCH-$TRAVIS_COMMIT
    - docker logout